name: vast-challenge

services:
  database:
    image: neo4j:5.18 # Using a slightly older but stable version
    container_name: vast-challenge-database
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/ava25-DB!!
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_bolt_enabled=true
      - NEO4J_server_http_enabled=true
      - NEO4J_server_https_enabled=false

  frontend:
    container_name: vast-challenge-frontend
    image: vast-challenge-frontend:latest
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    environment:
      # VITE_BACKEND_URL is a common convention for Vite env vars
      VITE_BACKEND_URL: "http://vast-challenge-backend:8080"
      PRODUCTION: "true"
    ports:
      - "5173:5173" # Map host 5173 to container's Vite dev port 5173

  backend:
    build: ./backend
    container_name: vast-challenge-backend
    image: vast-challenge-backend:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=vast-challenge-database
      - DB_PASSWORD=ava25-DB!!
      - PRODUCTION=true